config/routes.rb
ProjectRedChambon::Application.routes.draw do

 get "events/map"
 get "sponsorships/map"

 post "events/:id/save_block" => "events#save_block"
 post "events/:id/save_block_order" => "events#save_block_order"
 post "events/create_block" => "events#create_block"
 post "events/create_section" => "events#create_section"
 post "events/create_sponsorship_block" => "events#create_sponsorship_block"
 post "events/destroy_block" => "events#destroy_block"
 

 get  "events/:id/edit_step2" => "events#edit_step2"
 
 post "admin/volunteers" => "admin#volunteers"
 post "admin/sponsors" => "admin#sponsors"

 get "admin/event/:id/edit" => "events#edit"
 get "admin/event/new" => "events#new"
 
 resources :events 

 resources :brands

 resources :sponsorships

 resources :pictures, only: [:create, :destroy]

get "home/index"
get "home/contact"
get "home/about"

get "admin/index"
get "admin/new"

match "home" => "home#index"
match "events" => "events#index"
match "admin" => "admin#index"

get 'tags/:tag', to: 'events#index', as: :tag

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "oauth_callbacks"} #omniauth_callbacks

  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base

  attr_accessible :date_end, :date_start, :description, :industry_id, :location, :rating, :title, :user_id, :image, :latitude, :longitude, :tag_list, :pictures, :image_url

  belongs_to :user
  belongs_to :industry
  belongs_to :event_type
  has_many :sections, :order => 'position ASC', :dependent => :destroy
  has_many :blocks, :through => :sections
  has_many :pictures, :as => :imageable, :dependent => :destroy

  accepts_nested_attributes_for :pictures
  before_create :init
  acts_as_taggable

  # mount_uploader :image, ImageUploader

  #validate :date_validation
  #validates :title, :presence => true

  def date_validation
    if !date_start.blank? and date_start < Date.today
      errors.add(:date_start, "can't be in the past")
    end
    if !date_end.blank? and date_end < Date.today
      errors.add( :date_end, "can't be in the past")
    end
    #if !date_start.blank? and !date_end.blank?
  end

  def image_url
    return self.image
  end
    

  private
  def init
    self.image = "/assets/no_event_image.jpg" if self.image.blank?
  end


  # private
  # def init
  #   self.date_start = Date.today + 10.days if self.date_start.nil?
  #   self.date_end = Date.today + 10.days if self.date_end.nil?
  # end


end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  has_many :events
  attr_accessible :description, :name
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  # GET /events
  # GET /events.json
  before_filter :authenticate_user!, except: [:index]
  def index
    if params[:tag]
       @events = Event.tagged_with(params[:tag]).order(:id).page(params[:page]).per_page(3)
     else
       @events = Event.order(:id).page(params[:page]).per_page(3)
    end

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @events }
    # end
  end

  def map
    @events = Event.all
    @features_as_json = events_as_json(@events)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @features_as_json }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show    
    @event = Event.find(params[:id], :include => [:blocks, :sections, :pictures, :industry])
    Rails.logger.debug("My object: #{@event.inspect}")
    @event.sections.each do |section|
      section.blocks.each do |block|
        block.details =  ActiveSupport::JSON.decode(block.details)
      end
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new #(title: "Awesome event", description: "tralala", sections: {Section.new(), Section.new()})
#Event.find(6, :include => [{:sections => :blocks}, :sections])


     respond_to do |format|
       format.html # new.html.erb
       #format.json { render partial: "new.json" } #render json: @event
       # format.json { render json: {
       #      'mata' => 'test',
       #      'workspace' => render_to_string(partial: "new.html", locals: {event: @event})
       #    }
       #  }
     end
  end

  # GET /events/1/edit
  def edit

    @event = Event.find(params[:id], :include => [:blocks, :sections, :pictures, :industry])

    @event.sections.each do |section|
      section.blocks.each do |block|
        block.details =  ActiveSupport::JSON.decode(block.details)
      end
    end

    respond_to do |format|
      format.html 
      # format.json { render json: {
      #       'mata' => 'test',
      #       'action' => 'edit',
      #       'eventId' => @event.id,
      #       'workspace' => render_to_string(partial: "new.html", locals: {event: @event})
      #     }
      # }
    end

    # @event = Event.find(params[:id])
    # respond_to do |format|
    #   format.html { render }
    #   format.json { render json: {
    #       'mata' => 'test',
    #       'action' => 'edit',
    #       'eventId' => @event.id,
    #       'workspace' => render_to_string(partial: "new.html", locals: {event: @event})
    #     }
    #   }
    # end
  end

  # GET /events/1/edit_step2
  def edit_step2
    @event = Event.find(params[:id], :include => [{:sections => :blocks}, :sections])

    @event.sections.each do |section|
      section.blocks.each do |block|
        block.details =  ActiveSupport::JSON.decode(block.details)
      end
    end

    respond_to do |format|
      format.json { render json: {
          'mata' => 'test',
          'action' => 'edit_step2',
          'eventId' => @event.id,
          'workspace' => render_to_string( partial: "show", locals: { event: @event, edit_mode: false }, formats: [:html])
        }
      }
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.title = "Event title"
    @event.description = "Awesome description for your event"
    @event.date_start = Date.today + 10.days;
    @event.date_end = Date.today + 12.days;

    @event.user_id = current_user.id

    @section_basic = Section.new(name: "Details", type_id: 1, position: 1)
    @section_details = Section.new(name: "People", type_id: 2, position: 2)
    @section_sponsorships = Section.new(name: "Sponsorships", type_id: 3, position: 3)
    @section_participants = Section.new(name: "Participants", type_id: 2, position: 4)

    @event.sections << @section_basic << @section_details << @section_sponsorships << @section_participants


    @block1 = Block.new(type_id: 1, position: 0)
    @block11 = Block.new(type_id: 2, position: 1)
    @section_basic.blocks << @block1 << @block11
    @block2 = Block.new(type_id: 1, position: 0)
    @block22 = Block.new(type_id: 2, position: 1)
    @section_details.blocks << @block2 << @block22
    @block3 = Block.new(type_id: 1, position: 0)
    @block33 = Block.new(type_id: 2, position: 1)
    @section_sponsorships.blocks << @block3 << @block33
    @block4 = Block.new(type_id: 1, content: "Some of participants", position: 0)
    @block44 = Block.new(type_id: 6, position: 1)
    @section_participants.blocks << @block4 << @block44

    respond_to do |format|
      if @event.save
      #   format.html { render partial: "test" } #{ redirect_to @event, notice: 'Event was successfully created.' }
      #   format.json { render json: @event, status: :created, location: @event }
      #   format.js { render "test" }
      # else
        format.html { redirect_to edit_event_path(@event) }
      #   format.json { render json: @event.errors, status: :unprocessable_entity }       format.json { render json: {
        # format.json { render json: {
        #       'mata' => 'test',
        #       'action' => 'edit',
        #       'eventId' => @event.id,
        #       'workspace' => render_to_string(partial: "new.html", locals: {event: @event})
        #     }
        #   }
      else
        format.html { render text: "am futut-o" }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id], :include => [{:sections => :blocks}, :sections])

    @event.sections.each do |section|
      section.blocks.each do |block|
        block.details =  ActiveSupport::JSON.decode(block.details)
      end
    end

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to edit_event_path(@event) }
        format.json { render json: {
            'mata' => 'test',
            'edit_guidelines' => render_to_string( partial: "edit_guidelines", locals: { edit_mode: true }, formats: [:html]),
            'edit_basic' => render_to_string( partial: 'edit_basic', locals: { event: @event }, formats: [:html]),
            'event_show' => render_to_string( partial: "show", locals: { event: @event, edit_mode: true }, formats: [:html])
          }
        }
      else
        format.html { render text: "am futut-o" }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end


######################
# Block operations
######################

  def create_block
    type_id = block_type_id(params[:type])
    @block = Block.new(type_id: type_id, section_id: params[:sectionId])
    if @block.save
      @block.details =  ActiveSupport::JSON.decode(@block.details)
      render partial: "event_block.html", locals: { block: @block, edit_mode: true } 
      #render json: @block
    else
      
    end
  end

  def create_section
    @section = Section.new(params[:section])

    @block1 = Block.new(type_id: 1, position: 0)
    @block11 = Block.new(type_id: 2, position: 1)
    @section.blocks << @block1 << @block11

    if @section.save
      @section.blocks.each do |block|
        block.details =  ActiveSupport::JSON.decode(block.details)
      end

      render json: { 'new_section' => render_to_string( partial: "event_section", locals: { event_section: @section, edit_mode: true, new_object: true }, formats: [:html]) }

    else
      render text: "error"
    end
  end

  def create_sponsorship_block
    type_id = block_type_id(params[:type])
    @block = Block.new(type_id: type_id, section_id: params[:sectionId])
    if @block.save
      render partial: "event_block.html", locals: { block: @block, edit_mode: true } 
    else
      
    end
  end

  def save_block
    @block = Block.find(params[:id])
    @block.update_attributes({
              content: params[:content], 
              position: params[:position],
              details: params[:details]})
    respond_to do |format|
      format.json { render json: @block }
    end
  end

  def save_block_order
    #@section = Section.find(params[:id], :include => [:blocks])
    old_order = params[:oldOrder].to_i
    new_order = params[:newOrder].to_i

    #block_1 = @section.blocks[@section.blocks.index{|block| block.id == old_order}]
    #block_2 = @section.blocks[@section.blocks.index{|block| block.id == new_order}]3
    block_1 = Block.where(section_id: params[:id]).where(position: params[:oldOrder]).first
    block_2 = Block.where(section_id: params[:id]).where(position: params[:newOrder]).first

    if block_1.nil? || block_2.nil?
      render json: {'error' => "could not save"} and return
    end

    block_1.position = new_order
    block_2.position = old_order
    block_1.save
    block_2.save

    render json: {'error' => 0} 
  end

  def destroy_block
    @block = Block.find(params[:id]);
    
    @block.delete
    @blocks = Block.select("id, position").where("section_id = ? AND position > ?", @block.section_id, @block.position)
    
    @blocks.each do |bl|
      bl.decrement!(:position)
    end
    render json: { "error" => 0 } and return

  rescue
    render json: { "error" => 1, "description" => "Could not delete block" } and return

  end

  private
  def fix

    
    blocks = Block.all(:conditions => "section_id IS NULL ")
    blocks.each do |block|
      block.delete
    end    

    #fix empty dates
    events = Event.all(:conditions => "date_start IS NULL OR date_end IS NULL")
    events.each do |event|
      event.date_start = Date.today + 10.days;
      event.date_end = Date.today + 12.days;
      event.save
    end 

    sections = Section.all

app/helpers/events_helper.rb
module EventsHelper

	#la asta trebuie renuntat. se va renda tot in event_block
	def block_content(block) 
		t = ""
		case block.type_id
		  when 1  #header
		  	t = "<h2>#{block.content}</h2>"
		  when 2  #text
		  	t = "<p>#{block.content}</p>"
		  when 3
		  	t = ""
		  when 4  #sponsorship
		  	t = render( partial: "event_block_sponsorship", locals: { sponsorships: block.details, block_id: block.id }, formats: [:html] )
		  when 5  
		  	t = "#{block.content}"		  
		  when 6
		  	t = render( partial: "event_block_participants", formats: [:html], locals: { friends: get_fb_friends(current_user)} )
	  end	
	 	return t.html_safe
	end

	def block_type(id)
		t = ""
		case id
		  when 1
		  	t = "header"
		  when 2
		  	t = "text"
		  when 3
		  	t = "image"
		  when 4
		  	t = "sponsorship"
		  when 5
		  	t = "media"
		  when 6
		  	t = "participants"
	  end	
	  return t
	end
	
	def block_type_id(type)
		case type
			when "header"
				return 1
			when "text"
				return 2
			when "image"
				return 3
			when "sponsorship"
				return 4
			when "media"
				return 5
			when "participants"
				return 6
		end
		return 0
	end

	def section_image(section)
		case section.type_id
			when 1
				return "/assets/bubble/icon-sheet.png"
			when 2
				return "/assets/bubble/icon-volunteers.png"
			when 3
				return "/assets/bubble/icon-message.png"
			when 4
				return "/assets/bubble/icon-plus.png"
			when 5
				return "/assets/bubble/icon-sheet.png"
		end
	end 


	#details is a hash of toggles
	#ex: {"align"=>"align-justify"} 
	#calling with type="align"
	#will render: data-field="align" data-value="align-center"
	def data_toggle_decode(block, type)
		if block.nil? || type.nil?
			return
		end
		toggle = ""
		toggle << "data-field=\"#{type}\" data-value=\""
		toggle << data_toggle_value(block, type)
		toggle << "\""
		return toggle.html_safe
	end

	def data_toggle_value(block, type)
		if block.nil? || type.nil?
			return
		end
		toggle = ""
		if !block.details.nil? && block.details.kind_of?(Hash) && block.details.has_key?(type.to_s) 
			toggle << "#{block.details[type.to_s]}"
		else
			#this should never be hit
			case type.to_s
				when "align"
					toggle << "align-left"
				when "size"
					toggle << "size-large"
			end 
		end
		return toggle.html_safe
	end

	def add_class_data_toggle(block)
		if block.nil? || block.details.blank? || !block.details.kind_of?(Hash)
			return
		end

		_block_type = block_type(block.type_id)
		class_text = " "

		block.details.each do |key, value|
			class_text << "#{_block_type}-#{value} "
		end

		return class_text.html_safe
	end

	def events_as_json(events)
	  events.collect do |event|
	    {
	      geometry: {
	      		type: "Point",
	      		coordinates: [event.longitude, event.latitude]
	      	},
	      properties: {
	      		:'marker-color' => get_industry_color(event.industry_id),
	      		id: event.id,
	      		title: event.title,
	      		feature_type: "event",
	      		description: event.description,
	      		industry: get_industry_name(event.industry),
	      		location: event.location,
	      		rating: event.rating,
	      		date_start: event.date_start,
	      		image: event.image_url().to_s
	      }
	    }
	  	end.to_json.html_safe
    end

    private
    def get_industry_color(industry_id)
    	color = ""
    	case industry_id.to_s
    		when "1"
    			color = "#A200FF"
    		when "2"
    			color = "#FF0097"
    		when "3"
    			color = "#00ABA9"
    		when "4"
    			color = "#8CBF26"
    		when "5"
    			color = "#1BA1E2"
    		when "6"
    			color = "#339933"	
    	end
    	return color
    end

	private
	def get_name(property, default_value)
		if property.nil? || property.name.nil? || property.name.blank?
			return default_value
		end
		return property.name
	end

	def get_industry_name(property)
		return get_name(property, "General")
	end

	def section_icon_class(type_id)
		t = ""
		case id
		  when 1
		  	t = "basic"
		  when 2
		  	t = "details"
		  when 3
		  	t = "sponsorship"
	  end	
	  return t
	end

	def symbolize_keys_deep!(h)
    h.keys.each do |k|
        ks    = k.respond_to?(:to_sym) ? k.to_sym : k
        h[ks] = h.delete k # Preserve order even when k == ks
        symbolize_keys_deep! h[ks] if h[ks].kind_of? Hash
    end
	end

	# def image_url(url)
	# 	if url.blank?
	# 		url = "no_image.jpg"
	# 	end
	# 	return File.join("/assets", url)
		
	# end

end
# "geometry": { "type": "Point", "coordinates": [-77.03, 38.90]},
#           "properties": {
#               "marker-color": "#000",
#               "marker-symbol": "star-stroked",
#               "image": "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/DCmontage4.jpg/250px-DCmontage4.jpg",
#               "url": "http://en.wikipedia.org/wiki/Washington,_D.C.",
#               "city": "Washington, D.C.",
#               "category": "awesome"

app/views/events/_event.html.erb
<!-- <li class="span4" style="style:none"> -->
    <div class="thumbnail thumbnail-first">	 
			
           <img style="width:460px;" src="<%= event.image.to_s %>"> <!--%= event.image_url(:thumb).to_s %-->
                <div class="mask">
                    <h4> <i class="icon icon-tag"></i> <%= get_industry_name(event.industry) %></h4>
                    <p id="_event_description"> <%= event.description.to_s %></p> 
                    <h4 id="_event_location" class="pull-left"><i class="icon icon-map-marker"></i> <%= event.location %></h4>
            </div>  
            </img>

		   <div class="when">
                <img src="<%= asset_path 'icon-fb.png' %>"></img>
                <img src="<%= asset_path 'icon-twitter.png' %>"></img>
                <img src="<%= asset_path 'icon-pinterest.png' %>"></img> 
            </div>

    		<div class="caption">
    			<a href="<%= "/events/#{event.id}" %>"><h2 id="_event_title"><%= event.title.to_s %></h2></a>
                <h3 class="pull-right"><i class="icon icon-calendar"></i> <%= "#{event.date_start.strftime('%d')}-#{event.date_end.strftime('%d')}" %> <small><%= "#{event.date_end.strftime('%b')}, #{event.date_end.strftime('%Y')}" %> </small></h3>
    		</div>	 
    </div>
    <div class="thumbnail-info">
        <h6> <i class="icon-user icon-white"></i>3453</h6>
        <h6> <i class="icon-eye-open icon-white"></i>34</h6>
        <h6> <i class="icon-tag icon-white"></i>3453</h6>
    </div>
<!-- </li> -->

app/views/events/_event_block.html.erb
<li id="bk<%= block.id %>" class="element <%= block_type(block.type_id) %>" data-type="<%= block_type(block.type_id) %>"  >

<% if edit_mode %>

	<%= render partial: "event_block_edit_toolbox", locals: { block: block }, formats: [:html] %>

	<% if block.type_id < 3 %>
		<textarea id="bk<%= block.id %>-body" class="<%= add_class_data_toggle(block) %>" style="display: none;" >
			<%= block_content(block) %>
		</textarea>
	<% end %>

	<% if block.type_id == 4 %>
		<div id="bk<%= block.id %>-body" class="<%= add_class_data_toggle(block) %>">
			<%= block_content(block) %>
		</div>
	<% end %>

	<% if block.type_id == 5 %>
		<div id="bk<%= block.id %>-body" class="meda_holder">
			<%= render partial: "event_block_embed_add", formats: [:html] %>
			<div id="bk<%= block.id %>-content" class="media-target">
				<%= block_content(block) %>
			</div>
		</div>
	<% end %>

	<% if block.type_id == 6 %>
		<div id="bk<%= block.id %>-body" class="">
			<!--%= render partial: "event_block_embed_add", formats: [:html] %-->
			<div id="bk<%= block.id %>-content" class="">
				<%= block_content(block) %>
			</div>
		</div>
	<% end %>

	<script type="text/javascript">
		$(document).ready( function() {
			initialize<%= block_type(block.type_id).capitalize %>( "bk<%= block.id %>" );
			<% if block.type_id == 4 %>
				<%= "sponsorships_data_#{block.id} =  #{block.details.to_json}".html_safe %>;
			<% end %>
		});
	</script>

<% else %>

	<div id="bk<%= block.id %>_body" class="<%= add_class_data_toggle(block) %>" >
		<%= block_content(block) %>
	</div>

<% end %>

</li>

app/views/events/_event_block_embed_add.html.erb
<div class="media_add" style="display:none;">

	<div class="media-contain_top form_bubble">
		
			<!-- <span style="display: block; position: absolute; left: -9999px;" class="media-target"></span> -->
		
			<!-- <span class="media_title">Add media into your Tackk</span> -->
			<p>Embed media into your event</p>
			
			<p><small>It's easy to embed videos, songs, photos, and anything else found on the web. Just paste a link to your Youtube, Vimeo, Hulu, Instagram, or Soundcloud.</small></p>

			<div class="control-group string optional">
	      <input type="text" class="media-link" placeholder="Paste Link to YouTube or Vimeo" style="margin:10px 0">
	    </div>
	    <button class="btn btn-green btn-save">Embed</button>

<!-- 												<div class="label_bubble"><input type="text" class="media-link text_input" name="media-link" onfocus="if(this.value == 'Paste Link to a YouTube, Instagram, Soundcloud&hellip;') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Paste Link to a YouTube, Instagram, Soundcloud&hellip;'; }" value="http://www.youtube.com/watch?v=F8kROkeRzrc" tabindex="-1"><a href="#embed" class="btn btn-embed_media">Embed</a></div> -->

		</div><!-- end: form.media-contain_top -->
			
<!-- 		<div class="media-contain_bottom">
			<span class="media-carrot"></span>
			
			<div class="media-examples">
			
				<span>Or try out some examples below, then use your own!</span>
				
				<ul>
					<li class="media-youtube"><a href="http://www.youtube.com/watch?v=F8kROkeRzrc" title="YouTube Video" class="media-fill">YouTube Video</a></li>
					<li class="media-vimeo"><a href="http://vimeo.com/7809605" title="Vimeo Video" class="media-fill">Vimeo Video</a></li>
					<li class="media-hulu"><a href="http://www.hulu.com/watch/336412/despicable-me-2" title="Hulu Video" class="media-fill">Hulu Video</a></li>
					<li class="media-instagram"><a href="http://instagr.am/p/JP4ur1RJAh/" title="Instagram Photo" class="media-fill">Instagram Photo</a></li>
					<li class="media-soundcloud"><a href="http://soundcloud.com/m83/midnight-city" title="Soundcloud Song" class="media-fill">Soundcloud Song</a></li>
					<li class="media-spotify"><a href="http://open.spotify.com/track/2v4dT8W8L7qNvpaTf3M4tJ" title="Spotify Song" class="media-fill">Spotify Song</a></li>
															</ul>
				
			</div> <!- - end: div.media-examples - ->
	
		</div> --><!-- end: div.media-contain_bottom -->

</div>

app/views/events/_event_block_participants.html.erb
<% friends.each do |friend| %>
	<div style="display:inline">
		<!--a href=""-->
			<img src="<%= "https://graph.facebook.com/#{friend['id']}/picture" %>" style="height:50px; width: 50px; margin:2px 0px 3px 0px" alt="<%= friend['name'] %>" title="<%= friend['name'] %>" data-rating="<%= Random.rand(100) %>" data-campaigns="<%= Random.rand(25) %>" />
		<!--/a-->
	</div>
<% end %>

app/views/events/_event_picture_preview.html.erb
<div style="height: 50px; width: 75px; float:left; margin:5px;">
  <img src="<%= picture.image_url(:thumb).to_s %>" />
</div>

app/views/events/_event_section_add.html.erb
<article class="post event-section" style="margin-bottom:100px;padding-bottom:50px;">
	<section style="background:transparent">
		<aside>
				<div class="bubble">
					 <img src="<%= asset_path 'bubble/icon-sheet.png' %>"/>
				</div>
				<a><h1 style="float:left;line-height:86px;margin:0"> New section </h1></a>
		</aside>
		<div class="article-content" style="margin:0;">			 
			 <a id="new_section" class="btn btn-large btn-blue">Add new section</a>
		</div>
	</section>
</article>
<article class="post event-section" style="margin-bottom:100px;padding-bottom:50px;">
	<section style="background:transparent">
		<aside>
			<div class="bubble">
				<img style="margin:0" src="<%= asset_path 'bubble/icon-message.png' %>"/>
			</div>
			<a><h1 style="float:left;line-height:86px;margin:0"> Comments section </h1></a>
		</aside>
		<div class="article-content" style="margin:0;">
			  <a id="new_custom_block" class="btn btn-blue btn-large" style="width:200px">Add comments</a>
		</div>
	</section>
</article>

app/views/events/_new_custom_block.html.erb
<div class="hide" id="new_custom_block_wrapper">
  <div class="modal-header">
    <h3>Create new block - <span style="color:#0099b5">select type</span></h3>
  </div>
  <div class="modal-body">
       <div class="square" style="width:auto;height:70px" data-type="sponsorship"> 
       <img style="margin-top:-5px;margin-bottom:0"  src=" <%= asset_path 'bubble/icon-sheet.png' %> ">
         <p style="line-height:1;padding:0 10px;">Sponsorship</p>
      </div>

      <div class="square" style="width:auto;height:70px" data-type=""> 
       <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-gift.png' %> ">
       <p style="line-height:1;padding:0 10px;">Awards & Prizes</p>
      </div>
      <div class="square" style="width:auto;height:70px" data-type=""> 
       <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-volunteers.png' %> ">
       <p style="line-height:1;padding:0 10px;"> People </p>
      </div>
      <div class="square" style="width:auto;height:70px" data-type=""> 
       <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-sheet.png' %> ">
       <p style="line-height:1;padding:0 10px;"> Other </p>
      </div>

  </div>
  <div class="pull-right" style="padding:0 0 15px 15px;">
    <button class="btn btn-danger btn-close" data-dismiss="modal" aria-hidden="true">Cancel</button>
  </div>
</div>

app/views/events/_new_section.html.erb
<div class="hide" id="new_section_wrapper">
  <div class="modal-header">
    <h3>Add a new section</h3>
  </div>
  <div class="modal-body">
      <input type="text" id="section_name" placeholder="Name" style="margin:10px 0">
      <legend>Choose an icon</legend>
      <div class="square selected" data-type="1"> 
        <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-sheet.png' %> ">
      </div>

      <div class="square" data-type="2"> 
        <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-volunteers.png' %> ">
      </div>
      <div class="square" data-type="3">
        <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-message.png' %> ">
      </div>
      <div class="square" data-type="4">
        <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-plus.png' %> ">
      </div>
      <div class="square" data-type="1"> 
        <img style="margin-top:-5px;height:35px; height:auto"  src=" <%= asset_path 'bubble/icon-sheet.png' %> ">
      </div>
  </div>
  <div class="pull-right" style="padding:0 0 15px 15px;">
    <button class="btn btn-green btn-save">Save</button>
    <button class="btn btn-danger btn-close">Cancel</button>
    
  </div>
</div>

app/views/events/_preview.html.erb
 <%= render partial: "show", locals: { edit_mode: true }, formats: [:html] %>

app/views/events/index.html.erb
<div id="wrapper">
	<div class="row-fluid">
		<ul id="events" class="thumbnails">
			<% @events.each do |event| %>
				<li class="span4" style="style:none">
					<%= render partial: "event", locals: { event: event }, formats: [:html] %>
				</li>
			<% end %>
		</ul>
	</div>

	<br />
	<br />
	<%= will_paginate @events %>

</div>
<!-- < %=  link_to 'New Event', new_event_path, :class => 'btn btn-primary' %> -->

app/views/events/show.html.erb
<%= render( partial: "show", locals: { event: @event, edit_mode: false }, formats: [:html]) %>
 <div class="back-to-top"></div>