config/routes.rb
ProjectRedChambon::Application.routes.draw do

 get "events/map"
 get "sponsorships/map"

 post "events/:id/save_block" => "events#save_block"
 post "events/:id/save_block_order" => "events#save_block_order"
 post "events/create_block" => "events#create_block"
 post "events/create_section" => "events#create_section"
 post "events/create_sponsorship_block" => "events#create_sponsorship_block"
 post "events/destroy_block" => "events#destroy_block"
 

 get  "events/:id/edit_step2" => "events#edit_step2"
 
 post "admin/volunteers" => "admin#volunteers"
 post "admin/sponsors" => "admin#sponsors"

 get "admin/event/:id/edit" => "events#edit"
 get "admin/event/new" => "events#new"
 
 resources :events 

 resources :brands

 resources :sponsorships

 resources :pictures, only: [:create, :destroy]

get "home/index"
get "home/contact"
get "home/about"

get "admin/index"
get "admin/new"

match "home" => "home#index"
match "events" => "events#index"
match "admin" => "admin#index"

get 'tags/:tag', to: 'events#index', as: :tag

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "oauth_callbacks"} #omniauth_callbacks

  root :to => "home#index"

end

app/models/sponsorship.rb
class Sponsorship < ActiveRecord::Base
  
  belongs_to :brand
  belongs_to :industry

  attr_accessible :date_end, :date_start, :description, :image, :industry_id, :latitude, :location, :longitude, :sponsorship_type_id, :title
end

app/controllers/sponsorships_controller.rb
class SponsorshipsController < ApplicationController
  # GET /sponsorships
  # GET /sponsorships.json
  include SponsorshipsHelper
  include EventsHelper
  def index
    @sponsorships = Sponsorship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sponsorships }
    end
  end

  # GET /sponsorships/1
  # GET /sponsorships/1.json
  def show
    @sponsorship = Sponsorship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sponsorship }
    end
  end

  def map

    @sponsorships = Sponsorship.all
    @features_as_json = sponsorships_as_json(@sponsorships)

    respond_to do |format|
      format.html { render action: "../events/map" }
      format.json { render json: @features_as_json }
    end

    
  end

  # GET /sponsorships/new
  # GET /sponsorships/new.json
  def new
    @sponsorship = Sponsorship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sponsorship }
    end
  end

  # GET /sponsorships/1/edit
  def edit
    @sponsorship = Sponsorship.find(params[:id])
  end

  # POST /sponsorships
  # POST /sponsorships.json
  def create
    @sponsorship = Sponsorship.new(params[:sponsorship])

    respond_to do |format|
      if @sponsorship.save
        format.html { redirect_to @sponsorship, notice: 'Sponsorship was successfully created.' }
        format.json { render json: @sponsorship, status: :created, location: @sponsorship }
      else
        format.html { render action: "new" }
        format.json { render json: @sponsorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sponsorships/1
  # PUT /sponsorships/1.json
  def update
    @sponsorship = Sponsorship.find(params[:id])

    respond_to do |format|
      if @sponsorship.update_attributes(params[:sponsorship])
        format.html { redirect_to @sponsorship, notice: 'Sponsorship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sponsorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsorships/1
  # DELETE /sponsorships/1.json
  def destroy
    @sponsorship = Sponsorship.find(params[:id])
    @sponsorship.destroy

    respond_to do |format|
      format.html { redirect_to sponsorships_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/sponsorships_helper.rb
module SponsorshipsHelper
	def sponsorships_as_json(sponsorships)
    	sponsorships.collect do |sponsorship|
    		{
    			geometry: {
    				type: "Point",
    				coordinates: [sponsorship.longitude, sponsorship.latitude]
    			},
    			properties: {
    				:'marker-color' => get_industry_color(sponsorship.industry_id),
    				id: sponsorship.id,
    				title: sponsorship.title,
                    feature_type: "sponsorship",
    				description: sponsorship.description,
    				industry: get_industry_name(sponsorship.industry),
    				location: sponsorship.location,
    				date_start: sponsorship.date_start
    			}
    		}
    	end.to_json.html_safe
    end
end

app/views/sponsorships/_form.html.erb
<%= simple_form_for(@sponsorship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :date_start %>
    <%= f.input :date_end %>
    <%= f.input :location %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :sponsorship_type_id %>
    <%= f.input :industry_id %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sponsorships/edit.html.erb
<h1>Editing sponsorship</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsorship %> |
<%= link_to 'Back', sponsorships_path %>

app/views/sponsorships/index.html.erb
<h1>Listing sponsorships</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Date start</th>
    <th>Date end</th>
    <th>Location</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Sponsorship type</th>
    <th>Industry</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sponsorships.each do |sponsorship| %>
  <tr>
    <td><%= sponsorship.title %></td>
    <td><%= sponsorship.description %></td>
    <td><%= sponsorship.date_start %></td>
    <td><%= sponsorship.date_end %></td>
    <td><%= sponsorship.location %></td>
    <td><%= sponsorship.latitude %></td>
    <td><%= sponsorship.longitude %></td>
    <td><%= sponsorship.sponsorship_type_id %></td>
    <td><%= sponsorship.industry_id %></td>
    <td><%= sponsorship.image %></td>
    <td><%= link_to 'Show', sponsorship %></td>
    <td><%= link_to 'Edit', edit_sponsorship_path(sponsorship) %></td>
    <td><%= link_to 'Destroy', sponsorship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sponsorship', new_sponsorship_path %>

app/views/sponsorships/new.html.erb
<h1>New sponsorship</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsorships_path %>

app/views/sponsorships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @sponsorship.title %>
</p>

<p>
  <b>Description:</b>
  <%= @sponsorship.description %>
</p>

<p>
  <b>Date start:</b>
  <%= @sponsorship.date_start %>
</p>

<p>
  <b>Date end:</b>
  <%= @sponsorship.date_end %>
</p>

<p>
  <b>Location:</b>
  <%= @sponsorship.location %>
</p>

<p>
  <b>Latitude:</b>
  <%= @sponsorship.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @sponsorship.longitude %>
</p>

<p>
  <b>Sponsorship type:</b>
  <%= @sponsorship.sponsorship_type_id %>
</p>

<p>
  <b>Industry:</b>
  <%= @sponsorship.industry_id %>
</p>

<p>
  <b>Image:</b>
  <%= @sponsorship.image %>
</p>


<%= link_to 'Edit', edit_sponsorship_path(@sponsorship) %> |
<%= link_to 'Back', sponsorships_path %>