config/routes.rb
ProjectRedChambon::Application.routes.draw do

 get "events/map"
 get "sponsorships/map"

 post "events/:id/save_block" => "events#save_block"
 post "events/:id/save_block_order" => "events#save_block_order"
 post "events/create_block" => "events#create_block"
 post "events/create_section" => "events#create_section"
 post "events/create_sponsorship_block" => "events#create_sponsorship_block"
 post "events/destroy_block" => "events#destroy_block"
 

 get  "events/:id/edit_step2" => "events#edit_step2"
 
 post "admin/volunteers" => "admin#volunteers"
 post "admin/sponsors" => "admin#sponsors"

 get "admin/event/:id/edit" => "events#edit"
 get "admin/event/new" => "events#new"
 
 resources :events 

 resources :brands

 resources :sponsorships

 resources :pictures, only: [:create, :destroy]

get "home/index"
get "home/contact"
get "home/about"

get "admin/index"
get "admin/new"

match "home" => "home#index"
match "events" => "events#index"
match "admin" => "admin#index"

get 'tags/:tag', to: 'events#index', as: :tag

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
                     controllers: {omniauth_callbacks: "oauth_callbacks"} #omniauth_callbacks

  root :to => "home#index"

end

app/models/brand.rb
class Brand < ActiveRecord::Base

  belongs_to :user
  has_many :sponsorships

  attr_accessible :contact_name, :description, :email, :latitude, :location, :logo, :longitude, :name, :phone_number, :user_id, :website
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= simple_form_for(@brand) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :email %>
    <%= f.input :logo %>
    <%= f.input :phone_number %>
    <%= f.input :website %>
    <%= f.input :location %>
    <%= f.input :latitude %>
    <%= f.input :longitude %>
    <%= f.input :contact_name %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Email</th>
    <th>Logo</th>
    <th>Phone number</th>
    <th>Website</th>
    <th>Location</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Contact name</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.name %></td>
    <td><%= brand.description %></td>
    <td><%= brand.email %></td>
    <td><%= brand.logo %></td>
    <td><%= brand.phone_number %></td>
    <td><%= brand.website %></td>
    <td><%= brand.location %></td>
    <td><%= brand.latitude %></td>
    <td><%= brand.longitude %></td>
    <td><%= brand.contact_name %></td>
    <td><%= brand.user_id %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
 <div class="row-fluid" > <!-- style="padding:30px 0"  -->
  <div class="span10 offset1">
    <div class="top-bar clearfix" style="-moz-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.15);
-webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.15);
box-shadow: 0 1px 1px rgba(0, 0, 0, 0.15);">

      <a class="profile-image" style="display: block;
                      float: left;
                      margin-right: 20px;">
          <img alt="Small_vapjpmb0a3bscmazj0du" src="http://www.pocketberry.com/wp-content/uploads/2009/11/COSMOTE2_08181806.bmp" width="200">            
      </a>
      <h2>Cosmote Romania</h2>
      <div class="cleafix">
        <ul class="stats">
          <li class="stat" style="padding-right:10px">
          <div class="value">12</div>
          <div class="descriptor">Events </div>
          </li>
          <li class="stat" style="width:150px;padding-right:10px;padding-left:20px">
          <div class="value">25</div>
          <div class="descriptor">Campaigns</div>
          </li>
          <li class="stat" style="padding-right:10px;padding-left:20px">
          <div class="value">3078</div>
          <div class="descriptor">Followers</div>
          </li>
          <li class="stat" style="width:160px;padding-right:10px;padding-left:20px">
          <div class="value">3</div>
          <div class="descriptor">Active sponsorships</div>
          </li>
        </ul>
      </div>

      <div style="float:right;height:120px;width:120px;margin-top:-40px;">
                    <canvas class="founded" id="canv3" width="120" height="120" data-size="medium">
                        <span class="iv">56</span>
                        <span class="ic">1</span>
                        <span class="ia">0</span>
                    </canvas>
                </div>
    </div>
  </div>
</div>

<!-- de aici bara meniu -->

<div class="navbar event-menu" style="margin-bottom:20px;">
  <div class="navbar-inner lite" >
    <div class="container">
        <div class="row">
          <div class="span10 offset1">
              <ul class="nav" style="margin-top:5px;">
                <li><%= link_to "Details" %></li>
                <li><%= link_to "Events" %></li>
                <li><%= link_to "Campaigns" %></li>       
                <li><%= link_to "Followers" %></li>
                <li><%= link_to "Active sponsorships" %></li>

              </ul>

              <ul class="nav pull-right" style="margin-top:5px;">
                <!-- <li style="margin-right:5px;" >
                     <input onclick="fillModal(2)" class="btn btn-green" type="button" data-toggle="modal" href="#modalSeed" value="Recommend Event">
                </li> -->
                <li>
                     <input class="btn btn-orange" type="button" data-toggle="modal" href="#modalVolunteer" value="Follow" >
                </li>
                <li><a data-toggle="modal" href="#modalMore">More +</a></li>
              </ul>
          </div>
        </div>
    </div>
  </div>
</div>

    <center>
    <h1>Sponsored by Cosmote</h1>
      <h1 style="margin-bottom:50px;"><small>Timeline of all past events and campaigns sponsored by Cosmote</small></h1>
    </center>

<!-- de aici in jos timeline -->

<div id="wrapper">
    <div class="sponsorship-timeline" style="padding-top:39px;margin-bottom:40px;padding-bottom:50px;">
      <span class="year">2012</span>

        <%= render partial: 'events/event_thumbnail.html'%>


        <%= render partial: 'events/event_thumbnail.html'%>


        <%= render partial: 'events/event_thumbnail.html'%>


        <%= render partial: 'events/event_thumbnail.html'%>

    </div>
</div>

<script type="text/javascript">

  $(document).ready(function () {
    var sliders = $(".seeds-graph-container");
          sliders.each(function(index, slider) {
              animate3(slider); 
          });

          var graphs = $('.founded');
          graphs.each(function (index, canvas) {
              animateCircle(canvas);
          });
  });
</script>